# Generated by Django 4.2 on 2023-05-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
