# Generated by Django 4.2 on 2023-05-01 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Видимость комментария'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercomments_item', to='app_users.item', verbose_name='Тема комментария'),
        ),
    ]
