# Generated by Django 4.2 on 2023-05-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_usercomment_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='item',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='usercomments_item', to='app_users.item', verbose_name='Тема комментария'),
        ),
    ]
